In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd

# movie, ratings by users
data = [
    [5, 4, 1, 1, 3],
    [3, 2, 1, 3, 1],
    [3, 3, 3, 3, 5],
    [1, 1, 5, 4, 4],
]
columns = ['Titanic', 'Tiffany', 'Terminator', 'Star Trek', 'Star Wars'] #movies
index = ['Ada', 'Bob', 'Steve', 'Margaret'] #users

R = pd.DataFrame(data, index=index, columns=columns).values

#create a model and set the hyperparameters
# model assumes R ~ PQ'
model = NMF(n_components=2, init='random', random_state=10)

model.fit(R)

Q = model.components_  # movie-genre matrix

P = model.transform(R)  # user-genre matrix

print(model.reconstruction_err_) #reconstruction error

nR = np.dot(P, Q)
print(nR) ## The reconstructed matrix!

# predict the hidden features for a new data point
query = [[1, 2, 5, 4, 5]]
#in this case, a new user providing ratings for the 5 movies.
new_query = model.transform(query)
R_pred = np.dot(new_query,Q)
R_pred = zip(columns, R_pred.T)

maximum = 0
film_recommendation = ''
for each in R_pred:
    if each[1] > maximum:
        maximum = each[1]
        film_recommendation = each[0]

film_recommendation


2.319822011025
[[4.98574011 3.98089613 0.69817861 1.52507923 2.84430572]
 [2.61580597 2.15486368 1.23495386 1.51110529 2.19736573]
 [3.35829506 2.89944467 3.32824145 3.36641177 4.23566511]
 [0.85105386 1.03300314 4.75334969 4.0532461  4.24705685]]


'Terminator'